name: backports

on:
  pull_request_target:
    types: [closed]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    # NOTE(mnaser): https://github.com/korthout/backport-action?tab=readme-ov-file#trigger-using-a-comment
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != 105816074 &&
        startsWith(github.event.comment.body, '/backport')
      )
    steps:
      - uses: wayfair-incubator/forker@eaae6dcbfb2c4724319ccee5beb89122414e6c69 # main
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          repo: ${{ github.event.repository.name }}
          owner: ${{ github.event.repository.owner.login }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          repository: vexxhost-bot/${{ github.event.repository.name }}
      - uses: korthout/backport-action@d07416681cab29bf2661702f925f020aaa962997 # v3.4.1
        with:
          github_token: ${{ secrets.VEXXHOST_BOT_PAT }}
          copy_labels_pattern: skip-release-notes
